# Project Metadata
sonar.organization=huypham67
sonar.projectKey=huypham67_bookmark-worker
sonar.projectName=bookmark-worker
sonar.projectVersion=1.0

# Scope & Encoding
sonar.sources=.
sonar.tests=.
sonar.sourceEncoding=UTF-8
